### ISSUE TITLE
The image size of inference

### ISSUE THREAD

**Issue by yousaLING** [williamyang1991/GP-UNIT#13]
Hello! Thanks for the great work!

I am currently using your GP-UNIT project and am impressed with its capabilities. However, I have encountered a question regarding the configuration of image sizes during the inference process.

As I was running the provided inference script, I noticed that the output images have a size of 256x256, even though the input images are resized to 512x512. I couldn't find explicit settings for the output image size in the provided code.

Perhaps this is related to this piece of code：
`     sampler = ICPTrainer(np.empty([0, 256]), 128)  `

But it seems that modifying this code will result in an error, so I found similar code during training as well.

`    W = np.empty([0, 256])   `

Could you please provide guidance on how to configure the output image size during inference? Additionally, I would like to inquire if it is necessary to adjust any settings related to image size during the training phase to ensure compatibility with the desired output size during inference.

I appreciate your assistance and look forward to your guidance on this matter!

**Comment by williamyang1991** [comment]
The 256 in ICPTrainer is not about image size. It is the dimension of the latent vector.


You need to change the dataset setting

https://github.com/williamyang1991/GP-UNIT/blob/d59695ee1534db44f42d5eb564615b1cfb253d2e/dataset.py#L190

https://github.com/williamyang1991/GP-UNIT/blob/d59695ee1534db44f42d5eb564615b1cfb253d2e/dataset.py#L251

https://github.com/williamyang1991/GP-UNIT/blob/d59695ee1534db44f42d5eb564615b1cfb253d2e/dataset.py#L351


And change some model setting

https://github.com/williamyang1991/GP-UNIT/blob/d59695ee1534db44f42d5eb564615b1cfb253d2e/model/content_encoder.py#L97-L98

Since our method is designed for 256x256 images, I'm not sure whether there are some other code that need to be changed.

**Comment by yousaLING** [comment]
All right, Thank you for your rapid reply!
